// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonial
          tag="Our Philosophy"
          quote="Efficiency is the bridge between aspiration and reality. In the modern service economy, being present is not enough—you must be responsive."
          author="Nazar Ulyanov"
          role="Founder, AutoClient Solutions"
          imageSrc="http://img.b2bpic.net/free-photo/portrait-bearded-black-man-wool-suit_613910-15972.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
