// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Begin Your Transformation"
          text="Ready to respond faster and scale your business with luxury AI systems?"
          primaryButton={{
            text: "Book a Free Review",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Contact Nazar",
            href: "#",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
