// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
        tag="Queries"
        title="Frequently Asked Questions"
        description="Everything you need to know about integrating AI automation into your luxury business."
        items={[
            {
              question: "Is AI automation 'robotic' or impersonal?",
              answer: "Our solutions are designed to sound human and maintain your unique brand voice, ensuring every interaction feels premium and personal.",
            },
            {
              question: "Which channels do you support?",
              answer: "We integrate with WhatsApp, Instagram, Facebook, and your existing email/website forms for unified client management.",
            },
            {
              question: "Is my data secure?",
              answer: "We prioritize enterprise-grade security, ensuring your client information and business data remain protected and private.",
            },
            {
              question: "Can this work for my small business?",
              answer: "Yes, our systems are scalable, designed for small-to-medium service businesses aiming for high-end growth and operational excellence.",
            },
          ]}
        imageSrc="https://picsum.photos/seed/123282607/1200/800"
      />
        </SectionErrorBoundary>
      </div>
  );
}
