// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
          tag="Luxury AI Automation"
          title="Stop Losing Customers to Slow Responses"
          description="Modern AI-powered systems that help businesses respond faster, qualify enquiries, automate communication, and stay available 24/7."
          primaryButton={{
            text: "Book a Free Review",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Learn More",
            href: "#about",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/empty-modern-workspace-with-advanced-technology-enhance-efficiency_482257-125614.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-handsome-businessman-sunglasses_1163-5525.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
