/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

const primaryButton = {
  text: "Book a Consultation",
  href: "#contact"
};
const secondaryButton = {
  href: "#services",
  text: "View Our Work"
};

type HeroSplitMediaGridProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  items: [
    { imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never },
    { imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never }
  ];
};

const HeroInline = () => {
  return (
    <section aria-label="Hero section" className="relative flex items-center h-fit md:h-svh pt-25 pb-20 md:py-0">
      <HeroBackgroundSlot />
      <div className="flex flex-col md:flex-row items-center gap-12 md:gap-20 w-content-width mx-auto">
        <div className="w-full md:w-1/2">
          <div className="flex flex-col items-center md:items-start gap-3">
            <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
              <p>{"Premium Websites. Intelligent Automation."}</p>
            </div>

            <TextAnimation
              text={"We build websites that grow businesses."}
              variant="fade-blur"
              gradientText={false}
              tag="h1"
              className="text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-center md:text-left text-balance"
            />

            <TextAnimation
              text={"High-end digital experiences crafted for luxury brands, medical practices, and premium service businesses."}
              variant="fade-blur"
              gradientText={false}
              tag="p"
              className="md:max-w-8/10 text-lg md:text-xl leading-snug text-center md:text-left text-balance"
            />

            <div className="flex flex-wrap max-md:justify-center gap-3 mt-2 md:mt-3">
              <Button text={primaryButton.text} href={primaryButton.href} variant="primary"/>
              <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary"animationDelay={0.1} />
            </div>
          </div>
        </div>

        <ScrollReveal variant="fade-blur" delay={0.2} className="w-full md:w-1/2 grid grid-cols-2 gap-2 xl:gap-3 2xl:gap-4">
          {[
            { imageSrc: "https://picsum.photos/seed/681772002/1200/800" },
            { imageSrc: "https://picsum.photos/seed/1500996022/1200/800" }
          ].map((item, index) => (
            <div key={index} className="h-80 md:h-[55vh] p-2 xl:p-3 2xl:p-4 card rounded overflow-hidden">
              <ImageOrVideo imageSrc={item.imageSrc} videoSrc={item.videoSrc} />
            </div>
          ))}
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
