// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Proven Impact"
          title="Scalable Performance Data"
          description="The metrics that drive your business growth, enabled by AutoClient."
          metrics={[
            {
              value: "400%",
              title: "Faster Response Time",
              features: [
                "Average response speed",
                "Immediate client touchpoints",
              ],
            },
            {
              value: "65%",
              title: "Lead Conversion Rate",
              features: [
                "Automated qualification flows",
                "Better sales targeting",
              ],
            },
            {
              value: "24/7",
              title: "Operational Availability",
              features: [
                "Never miss an enquiry",
                "Always-on communication",
              ],
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
