// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesRevealCardsBento
          tag="Our Automation Suite"
          title="Precision Business Solutions"
          description="Premium systems designed to scale your operational capacity while maintaining a white-glove client experience."
          items={[
            {
              title: "24/7 Intelligent Response",
              description: "Ensure no enquiry goes unacknowledged with AI systems that manage your communication around the clock.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/messy-office-workplace-workplace-workspace-concept_185193-109628.jpg",
            },
            {
              title: "Lead Qualification",
              description: "Automated protocols to filter and prioritize high-value enquiries, so your team focuses on closing.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/futurism-perspective-digital-nomads-lifestyle_23-2151252445.jpg",
            },
            {
              title: "CRM Integration",
              description: "Seamlessly bridge your client communication across Instagram, WhatsApp, and Facebook into one source of truth.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/desktop-pc-wooden-desk-showcases-infographics-client-reach-data_482257-126876.jpg",
            },
            {
              title: "Strategic Audits",
              description: "Deep analysis of your current manual processes to uncover hidden friction points and missed revenue.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/employee-examining-company-performance_482257-121856.jpg",
            },
            {
              title: "Operational Excellence",
              description: "Refining your client onboarding and internal processes to ensure professional, scalable consistency.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/artificial-intelligence-technology-simulating-human-brain-used-by-engineer_482257-122157.jpg",
            },
            {
              title: "Scalable Infrastructure",
              description: "Build foundations that grow with your business, supporting high volumes without compromising premium quality.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-ring-binder_23-2149568988.jpg",
            },
            {
              title: "Conversion Engineering",
              description: "Optimized communication workflows designed to convert more enquiries into booked appointments.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/global-communications-connection-discussion-interaction-concept_53876-21186.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
