// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeOverlayCards
          tag="Client Success"
          title="Luxury Partners"
          description="Entrepreneurs and consultants who elevated their growth through automation."
          testimonials={[
            {
              name: "Sarah Johnson",
              role: "CEO",
              company: "Elite Dental",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-happy-man-writing-document-bicycle-shop_23-2147892642.jpg",
            },
            {
              name: "Michael Chen",
              role: "Founder",
              company: "Prime Realty",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/modern-businesswoman_23-2148012909.jpg",
            },
            {
              name: "Emily Rodriguez",
              role: "Owner",
              company: "Serene Spa",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/call-center-agents-collaborating-track-lost-customers-shipments_482257-117820.jpg",
            },
            {
              name: "David Kim",
              role: "Consultant",
              company: "Growth Partners",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/view-student-cute-woman-smiling-camera_197531-33567.jpg",
            },
            {
              name: "Lisa Wang",
              role: "Owner",
              company: "Zen Clinic",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-redhead-bearded-male-small-cafe-with-lot-flowers-coffee-machine_613910-8899.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
